import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "./globals.css";

const editorial = localFont({
  src: [
    { path: "../public/fonts/editorial-new-font-family/PPEditorialNew-Ultralight-BF644b21500d0c0.otf", weight: "200", style: "normal" },
    { path: "../public/fonts/editorial-new-font-family/PPEditorialNew-UltralightItalic-BF644b214ff1e9b.otf", weight: "200", style: "italic" },
    { path: "../public/fonts/editorial-new-font-family/PPEditorialNew-Regular-BF644b214ff145f.otf", weight: "400", style: "normal" },
    { path: "../public/fonts/editorial-new-font-family/PPEditorialNew-Italic-BF644b214fb0c0a.otf", weight: "400", style: "italic" },
    { path: "../public/fonts/editorial-new-font-family/PPEditorialNew-Ultrabold-BF644b21500840c.otf", weight: "800", style: "normal" },
    { path: "../public/fonts/editorial-new-font-family/PPEditorialNew-UltraboldItalic-BF644b214faef01.otf", weight: "800", style: "italic" },
  ],
  variable: "--font-editorial",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${editorial.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
